name: CI/CD E-commerce 3D

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: action/setup-node@v4
        with:
          node-version: '20'

      - name: install backend dependencies
        uses: npm install
        working-directory: ./backend

      - name: Run backend tests
        run: npm test
        working-directory: ./backend
  buld-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend
      
      - name: build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist

  deploy-frontend:
    needs: build-and-test-frontend
    runs-on: ubuntu-latest
    environment: production
    setps:
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist
      - name: Deploy to vercel
        uses: amondnet/vercel-action@20
        with:
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}